# Generated by Django 5.2.11 on 2026-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('baking', 'Baking'), ('ready', 'Ready for pickup'), ('picked_up', 'Picked up'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
