# Generated by Django 5.2.11 on 2026-03-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 4 PM)'), ('evening', 'Evening (4 PM - 8 PM)'), ('night', 'Night (8 PM - 11 PM)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_message',
            field=models.CharField(blank=True, help_text='Message on Cake', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flavor_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
