# Generated by Django 5.2.11 on 2026-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_date_order_delivery_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('baking', 'Baking'), ('ready', 'Ready for pickup'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
