# Generated by Django 5.2.11 on 2026-02-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.CharField(help_text='e.g., 1kg, 500g', max_length=50)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('is_eggless', models.BooleanField(default=False)),
                ('customization_options', models.TextField(blank=True, help_text='List available options', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='accounts.sellerprofile')),
            ],
        ),
    ]
