# Generated by Django 5.2.11 on 2026-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='flavor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='cake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
